name: Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build-ubuntu:
    name: ubuntu-compile
    runs-on: ubuntu-20.04
    steps:

    - uses: actions/checkout@v3
      with:
        submodules: 'true'

    - uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install NPM Packages
      run: npm install

    - name: Transpile Typescript Server
      run: npm run build